config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users
    resources :services
    resources :rooms
    resources :room_calendars do
      get  :calendar, on: :collection
      get  :monthly, on: :collection
      get  :weekly, on: :collection
      member do
        post :to_dealday
        post :to_holiday
        post :to_hotday
        post :to_weekday
      end
    end

  end

  resources :dashboard

  resources :clients do
    get :search, on: :collection
  end

  resources :orders do
    get :search_clients, on: :collection
    get :list_services, on: :collection
    get :list_rooms, on: :collection
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member

    get :list_services_update, on: :collection
    get :list_rooms_update, on: :collection
    post :add_order_item, on: :member
    delete :remove_order_item, on: :member

    get :daily, on: :collection
    get :pending, on: :collection
    get :unpaid, on: :collection

    member do
      post :down_pay
      # post :full_pay
      post :check_in
      post :check_out
      post :suspend
      post :reorder
      post :cancel
    end
  end

  resources :statistics do
    get :daily, on: :collection
    get :weekly, on: :collection
    get :monthly, on: :collection
    get :yearly, on: :collection
  end

  resources :print do
    get :orders, on: :collection
    get :abstract, on: :collection
    get :clients, on: :collection
    get :export, on: :collection
  end

  # root 'dashboard#index'
  root 'admin/room_calendars#weekly'
end

app/models/client.rb
class Client < ApplicationRecord
  extend Utility

  validates_presence_of :name

  has_many :orders, dependent: :destroy
  scope :recent, -> { order("updated_at DESC")}

  # accepts_nested_attributes_for :orders

  # 輸出成csv格式 
  def self.to_csv(is_4_db=false, options = {})
    desired_columns = ["name", "sex", "mobile", "country", "id_no", "birthday", "job", "tel", "address", "email", "reminder", "note"]
    export_columns = ["姓名", "性別", "手機", "國別", "身分證/護照", "生日", "職業", "電話", "地址", "email", "提醒(外)", "備註(內)"]

    to_csv_string(desired_columns, export_columns)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:edit, :update, :destroy, :show]

  # 接待/客戶管理 -> 列出所有客戶
  def index
    if params.has_key?(:name)
      @search_name = params[:name]
      @clients = Client.recent.where('lower(name) LIKE ?', "%#{@search_name.downcase}%")
    else
      @clients = Client.recent
    end
  end

  # 接待/客戶管理 -> 依客戶查詢
  def search
    @search_name = params[:search_name] if params.has_key?(:search_name) && params[:search_name].present?
    @search_mobile = params[:search_mobile] if params.has_key?(:search_mobile) && params[:search_mobile].present?

    if @search_name.present? && @search_mobile.present?
      @clients = Client.where('lower(name) LIKE ?', "%#{@search_name.downcase}%").where('lower(mobile) LIKE ?', "%#{@search_mobile.downcase}%")
    elsif @search_name.present?
      @clients = Client.where('lower(name) LIKE ?', "%#{@search_name.downcase}%")
    elsif @search_mobile.present?
      @clients = Client.where('lower(mobile) LIKE ?', "%#{@search_mobile.downcase}%")
    else
      @clients = []
    end
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path , notice: "新增客戶(#{@client.name})成功"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path , notice: "更新客戶(#{@client.name})成功"
    else
      render :edit
    end
  end

  def destroy
    client_name = @client.name
    @client.destroy
    redirect_to clients_path, alert: "客戶(#{client_name})已刪除!"
  end


  private

  def client_params
    params.require(:client).permit(:name, :sex, :mobile, :country, :id_no, :birthday, :job, :tel, :address, :email, :reminder, :note)
  end

  def set_client
    @client = Client.find(params[:id])
  end



end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<tr>
  <td><%= link_to(client.name, client_path(client)) %></td>
  <td><%= client.sex %></td>
  <td><%= client.mobile %></td>
  <td><%= client.country %></td>
  <td><%= client.id_no %></td>
  <td><%= client.birthday %></td>
  <td><%= client.email %></td>
  <td><%= client.address %></td>
  <td><%= client.reminder %></td>
  <td><%= client.note %></td>
  <td>
    <%= link_to("編輯", edit_client_path(client), class: "btn btn-primary")%>
    <%= link_to("刪除", client_path(client), class: "btn btn-danger",
                  method: :delete, data: { confirm: "你確定要刪除嗎?" } )%>
  </td>
</tr>

app/views/clients/_form.html.erb
<%= simple_form_for client do |f| %>
  <div class="form-group">
    <%= f.input :name, required: true, input_html: { class: "form-control"}, autofocus: true %>
    <%= f.input :sex %>
    <%= f.input :mobile %>
    <%= f.input :country, as: :string %>
    <%= f.input :id_no %>
    <%= f.input :birthday, as: :string %>
    <%= f.input :email %>
    <%= f.input :tel %>
    <%= f.input :address %>
    <%= f.input :job %>
    <%= f.input :reminder %>
    <%= f.input :note %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/clients/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>編輯客戶</h2>

  <hr>
  <%= render "form", client: @client %>

</div>

app/views/clients/index.html.erb
<div class="col-md-12 col-md-offset-0">
  <h3>所有客戶列表</h3>
  <div class="group">
    <%= link_to("新增客戶", new_client_path, class: "btn btn-primary pull-right") %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>姓名</th>
        <th>性別</th>
        <th>手機</th>
        <th>國籍</th>
        <th>身分證/護照</th>
        <th>生日</th>
        <th>email</th>
        <th>地址</th>
        <th>提醒(外)</th>
        <th>備註(內)</th>
        <th>功能</th>
      </tr>
    </thead>
    <tbody>
       <%= render partial: "client", collection: @clients %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增客戶</h2>

  <hr>
  <%= render "form", client: @client %>

</div>

app/views/clients/search.html.erb
<div class="col-md-10 col-md-offset-1">
  <h3>搜尋客戶列表</h3>
  <div class="form-group search-form">
    <%= form_with url: search_clients_path, method: :get, local: true do |f| %>
      <%= f.label :search_name, "客戶名稱:" %>
      <%= f.text_field :search_name, value: @search_name %>
      <%= f.label :search_mobile, "客戶手機:" %>
      <%= f.text_field :search_mobile, value: @search_mobile %>
      <%= f.submit "查詢", class: "btn btn-primary" %>
    <% end %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>姓名</th>
        <th>性別</th>
        <th>手機</th>
        <th>國籍</th>
        <th>身分證/護照</th>
        <th>生日</th>
        <th>email</th>
        <th>地址</th>
        <th>提醒(外)</th>
        <th>備註(內)</th>
        <th>功能</th>
      </tr>
    </thead>
    <tbody>
       <%= render partial: "client", collection: @clients %>
    </tbody>
  </table>
</div>

app/views/clients/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <h3>客戶資料</h3>

  <%= render partial: "common/clienttable", locals:{ client: @client, show_note: true} %>

  <hr />
  <h4>客戶訂單資料</h4>
  <hr />
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>訂單狀態</th>
        <th>訂單入住日</th>
        <th>訂單退房日</th>
        <th>住房日期</th>
        <th>房號─房型</th>
        <th>來源</th>
        <th>人數</th>
        <th>房價</th>
        <th>加床</th>
        <th>服務費</th>
        <th>總額</th>
        <th>訂金</th>
        <th>信用卡</th>
        <th>餘額</th>
        <th>支付方式</th>
        <th>末4碼</th>
      </tr>
    </thead>
    <tbody>
      <% @client.orders.each do |order| %>
        <% order.room_items.each do |item| %>

        <% if (order.aasm_state == "order_placed" ||
               order.aasm_state == "down_paid"    ||
               order.aasm_state == "full_paid"    ||
               order.aasm_state == "order_pending") %>
          <tr data-link="<%= order_path(order) %>">
        <% else %>
          <tr>
        <% end %>
            <td><%= render_order_state(order) %></td>
            <td><%= order.checkin_date %></td>
            <td><%= order.checkout_date %></td>
            <td><%= item.day %></td>
            <td><%= item.name %></td>
            <td><%= order.source %></td>
            <td><%= item.adult_no + item.kid_no + item.baby_no %></td>
            <td><%= order.room_subtotal %></td>
            <td><%= order.bed_subtotal %></td>
            <td><%= order.service_subtotal %></td>
            <td><%= order.total %></td>
            <td><%= order.downpay %></td>
            <td><%= order.credit_card %></td>
            <td><%= order.balance %></td>
            <td><%= order.pay_type %></td>
            <td><%= order.pay_info %></td>
          </tr>
        <% end %>
      <% end %>

    </tbody>
  </table>

<%= link_to '返回', clients_path %>

</div>


<script type="text/javascript">

$("tr[data-link]").click(function() {
  window.location = $(this).data("link")
});

</script>