config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users
    resources :services
    resources :rooms
    resources :room_calendars do
      get  :calendar, on: :collection
      get  :monthly, on: :collection
      get  :weekly, on: :collection
      member do
        post :to_dealday
        post :to_holiday
        post :to_hotday
        post :to_weekday
      end
    end

  end

  resources :dashboard

  resources :clients do
    get :search, on: :collection
  end

  resources :orders do
    get :search_clients, on: :collection
    get :list_services, on: :collection
    get :list_rooms, on: :collection
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member

    get :list_services_update, on: :collection
    get :list_rooms_update, on: :collection
    post :add_order_item, on: :member
    delete :remove_order_item, on: :member

    get :daily, on: :collection
    get :pending, on: :collection
    get :unpaid, on: :collection

    member do
      post :down_pay
      # post :full_pay
      post :check_in
      post :check_out
      post :suspend
      post :reorder
      post :cancel
    end
  end

  resources :statistics do
    get :daily, on: :collection
    get :weekly, on: :collection
    get :monthly, on: :collection
    get :yearly, on: :collection
  end

  resources :print do
    get :orders, on: :collection
    get :abstract, on: :collection
    get :clients, on: :collection
    get :export, on: :collection
  end

  # root 'dashboard#index'
  root 'admin/room_calendars#weekly'
end

app/models/order.rb
class Order < ApplicationRecord
  extend Utility
  validates_presence_of :checkin_date, :checkout_date, :name

  belongs_to :client

  has_many :order_items, dependent: :destroy

  has_many :room_items,  -> { where( type: "RoomItem" ) }, class_name: "OrderItem"
  has_many :service_items, -> { where( type: "ServiceItem" ) }, class_name: "OrderItem"

  scope :recent, -> { order("created_at DESC")}

  # after_destroy :clear_room_calendars
  after_save :update_room_calendars
  # after_commit :update_room_calendars

  def update_room_calendars
    room_items.each do |item|
      item.update_room_calendar
    end
  end

  def clear_room_calendars
    room_items.each do |item|
      item.clear_room_calendar
    end
  end

  def is_old_client?
    client_id.present?
  end

  def copy_client_data(client)
    client.name     = name
    client.sex      = sex
    client.mobile   = mobile
    client.country  = country
    client.id_no    = id_no
    client.birthday = birthday
    client.job      = job
    client.tel      = tel
    client.address  = address
    client.email    = email
    client.reminder = reminder
    client.note     = note
  end

  def build_items_from_cart(cart)
    cart.cart_items.each do | cart_item |
      if cart_item.kind == CartItem::Service_Type
        item = OrderItem.new(type: "ServiceItem", day: cart_item.day, name: cart_item.name, price: cart_item.price,
          item_id: cart_item.item_id)
        order_items << item
      elsif cart_item.kind == CartItem::Room_Type
        item = OrderItem.new(type: "RoomItem", day: cart_item.day, name: cart_item.name, price: cart_item.price,
          item_id: cart_item.item_id, add_bed_no: cart_item.add_bed_no, add_bed_fee: cart_item.add_bed_fee,
          adult_no: cart_item.adult_no, kid_no: cart_item.kid_no, baby_no: cart_item.baby_no)
        order_items << item
      end
    end
  end

  include AASM
  aasm do
    state :order_placed, initial: true
    state :down_paid
    state :full_paid
    state :checked_in
    state :checked_out
    state :order_pending
    state :order_cancelled

    event :down_pay do
      transitions from: :order_placed,                to: :down_paid
    end

    event :full_pay do
      transitions from: [:order_placed, :down_paid],  to: :full_paid
    end

    event :check_in do
      transitions from: [:order_placed, :down_paid, :full_paid], to: :checked_in
    end

    event :check_out do
      transitions from: :checked_in,                  to: :checked_out
    end

    event :suspend do
      transitions from: [:order_placed, :down_paid, :full_paid],  to: :order_pending
    end

    event :reorder do
      transitions from: :order_pending,               to: :order_placed
    end

    event :cancel do
      transitions from: :order_pending,               to: :order_cancelled
    end
  end

  # 輸出成csv格式 
  def self.to_csv(is_4_db=false, options = {})
    desired_columns = ["checkin_date", "checkout_date", "aasm_state", "source",
      "name", "sex", "mobile", "country", "id_no", "birthday", "job", "tel", "address", "email", "reminder", "note",
      "room_subtotal", "bed_subtotal", "service_subtotal", "total", "downpay", "credit_card", "balance",
      "pay_type", "pay_info", "adult_subtotal", "kid_subtotal", "baby_subtotal"]
    export_columns = ["入住日", "退房日", "狀態", "來源",
      "姓名", "性別", "手機", "國別", "身分證/護照", "生日", "職業", "電話", "地址", "email", "提醒(外)", "備註(內)",
      "房費小計", "加床小計", "服務小計", "總額", "訂金", "信用卡", "餘額",
      "支付方式", "末五碼", "大人人數", "小孩人數", "幼兒人數"]

    to_csv_string(desired_columns, export_columns)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:edit, :update, :destroy, :show, :down_pay, :full_pay, :check_in, :check_out, :suspend, :reorder, :cancel]
  before_action :set_search_date, only: [:index, :daily]

  # 讓 view 也能用，要掛上helper_method
  helper_method :current_cart

  # 接待/客戶管理 -> 依日期查詢
  def index
    # if params.has_key?(:search_date) && params[:search_date].present?
    #   @search_date = Date.parse(params[:search_date])
    #   @orders = Order.where('checkin_date = ? OR (created_at >= ? and created_at <= ?)', @search_date, @search_date.beginning_of_day, @search_date.end_of_day)
    # else
    #   @orders = []
    # end
    @room_items = get_daily_room_items(@search_date)

  end

  # 訂房/訂單管理 -> 待處理訂單
  def pending
    @orders = Order.where('aasm_state = ?', "order_pending")
  end

  # 訂房/訂單管理 -> 未付訂清單
  def unpaid
    @orders = Order.where('aasm_state = ?', "order_placed")
  end

  # 接待/客戶管理 -> Check-in(當日入住名單)
  def daily
    @orders = get_daily_room_orders(@search_date)
    # @room_items = get_daily_room_items(@search_date)
    # @room_items = OrderItem.where("type='RoomItem' AND day = ?", @search_date)
  end

  # 接待/客戶管理 -> 訂單登入
  def new
    current_cart.clean!

    if params.has_key?(:client_id)
      @client = Client.find(params[:client_id])
      @order = @client.orders.build(name: @client.name, sex: @client.sex, mobile: @client.mobile,
        country: @client.country, id_no: @client.id_no, birthday: @client.birthday, job: @client.job,
        tel: @client.tel, address: @client.address, email: @client.email,
        reminder: @client.reminder, note: @client.note)
    else
      @client = Client.new
      @order = @client.orders.build
      # @order = Order.new
    end
  end

  # 接待/客戶管理 -> 訂單登入(儲存)
  def create
    @order = Order.new(order_params)
    @order.created_by = current_user.name

    # 是否為現有客戶
    if @order.is_old_client?
      @client = Client.find(@order.client_id)
    else
      @client = Client.new
    end

    @order.build_items_from_cart(current_cart)
    # 檢查是否有訂房
    if @order.order_items.size < 1
      flash[:warning] = "訂房不可為空白！"
      redirect_back fallback_location: new_order_path(@order)
    else
      @client.orders << @order

      @order.copy_client_data(@client)
      if @client.save
        current_cart.clean!

        redirect_to order_path(@order), notice: "新增訂單(#{@order.name})成功"
        # redirect_to weekly_admin_room_calendars_path, notice: "新增訂單(#{@order.name})成功"
      else
        current_cart.clean!

        flash[:warning] = "新增訂單(#{@order.name})失敗"
        render :new
      end
    end

  end

  # 搜尋客戶資料
  def search_clients
    if params.has_key?(:name)
      @search_name = params[:name]
      @clients = Client.where('lower(name) LIKE ?', "%#{@search_name.downcase}%")
    else
      @clients = []
    end
  end

  # 列出房間服務
  def list_services
    @order_days = get_order_dates
    @services = Service.all
  end

  # 列出房間服務-Update
  def list_services_update
    list_services
    @order = Order.find(params[:order_id])
    @back_path = edit_order_url(@order)
  end

  # 列出房間列表-update
  def list_rooms_update
    list_rooms
    @order = Order.find(params[:order_id])
    @back_path = edit_order_url(@order)
  end

  # 列出房間列表
  def list_rooms
    @order_days = get_order_dates
    @calendar_items = get_room_items(@order_days)
  end

  def current_cart
    @current_cart ||= find_cart
  end

  def add_to_cart
    if params[:cart_item][:kind].present? && params[:cart_item][:kind] == CartItem::Service_Type
      @kind = CartItem::Service_Type
      service_item = CartItem.new(day: params[:cart_item][:day], kind: @kind,
        name: params[:cart_item][:name], price: params[:cart_item][:price], item_id: params[:id])
      @cart_item = current_cart.add_item_to_cart(service_item)
    end

    if params[:cart_item][:kind].present? && params[:cart_item][:kind] == CartItem::Room_Type
      @kind = CartItem::Room_Type
      room_item = CartItem.new(day: params[:cart_item][:day], kind: @kind,
        name: params[:cart_item][:name], price: params[:cart_item][:price],
        add_bed_no: params[:cart_item][:add_bed_no], add_bed_fee: params[:cart_item][:add_bed_fee],
        adult_no: params[:cart_item][:adult_no], kid_no: params[:cart_item][:kid_no],
        baby_no: params[:cart_item][:baby_no], item_id: params[:cart_item][:item_id])
      @cart_item = current_cart.add_item_to_cart(room_item)

      @td_id = "#{room_item.day}-#{room_item.item_id}"
    end
      # redirect_back fallback_location: product_path(@product)
  end

  def remove_from_cart
    @cart_item = CartItem.find(params[:id])
    # @kind = @cart_item.kind
    current_cart.remove_item_to_cart(@cart_item)
  end

  def remove_order_item
    @order_item = OrderItem.find(params[:id])
    @order = @order_item.order
    @order_item.destroy
    # 更新訂單金額數字
    recalculate_payment(@order)

    redirect_to edit_order_path(@order)
  end

  def add_order_item
    @order = Order.find(params[:order_id])

    if params[:cart_item][:kind].present? && params[:cart_item][:kind] == CartItem::Service_Type
      @kind = CartItem::Service_Type
      service_item = OrderItem.new(day: params[:cart_item][:day], type: "ServiceItem",
        name: params[:cart_item][:name], price: params[:cart_item][:price], item_id: params[:item_id])
      @order.order_items << service_item
      # 更新訂單金額數字
      recalculate_payment(@order)
    end

    if params[:cart_item][:kind].present? && params[:cart_item][:kind] == CartItem::Room_Type
      @kind = CartItem::Room_Type
      room_item = OrderItem.new(day: params[:cart_item][:day], type: "RoomItem",
        name: params[:cart_item][:name], price: params[:cart_item][:price],
        add_bed_no: params[:cart_item][:add_bed_no], add_bed_fee: params[:cart_item][:add_bed_fee],
        adult_no: params[:cart_item][:adult_no], kid_no: params[:cart_item][:kid_no],
        baby_no: params[:cart_item][:baby_no], item_id: params[:cart_item][:item_id])
      @order.order_items << room_item
      # 更新訂單金額數字
      recalculate_payment(@order)

      @td_id = "#{room_item.day}-#{room_item.item_id}"
    end

  end


  def show
  end

  def edit
    @client = @order.client
    current_cart.clean!
  end

  def update
    @client = Client.find(@order.client_id)
    @order.build_items_from_cart(current_cart)

    # 檢查是否有訂房
    if @order.order_items.size < 1
      flash[:warning] = "訂房不可為空白！"
      redirect_back fallback_location: edit_order_path(@order)
    else
      if @order.update(order_params)
        reload_order = Order.find(@order.id)
        reload_order.copy_client_data(@client)
        @client.save

        current_cart.clean!
        redirect_to weekly_admin_room_calendars_path, notice: "更新訂單(#{@order.name})成功"
      else
        current_cart.clean!

        flash[:warning] = "更新訂單(#{@order.name})失敗"
        render :edit
      end
    end
  end

  def destroy
    current_cart.clean!
    @order.destroy
    redirect_to weekly_admin_room_calendars_path, alert: "訂單(#{@order.name})已刪除!"
  end

  def down_pay
    @order.down_pay
    if @order.save
      redirect_to weekly_admin_room_calendars_path, notice: "訂單(#{@order.name})已付訂"
    else
      redirect_back fallback_location: order_path(@order)
    end
  end

  def check_in
    @order.check_in
    if @order.save
      redirect_to weekly_admin_room_calendars_path, notice: "訂單(#{@order.name})入住成功"
    else
      redirect_back fallback_location: order_path(@order)
    end
  end

  def check_out
    @order.check_out
    if @order.save
      redirect_to weekly_admin_room_calendars_path, notice: "訂單(#{@order.name})退房成功"
    else
      redirect_back fallback_location: order_path(@order)
    end
  end

  def suspend
    @order.suspend
    if @order.save
      redirect_to weekly_admin_room_calendars_path, notice: "訂單(#{@order.name})保留成功"
    else
      redirect_back fallback_location: order_path(@order)
    end

  end

  def reorder
    @order.reorder
    # @order.checkin_date = ""
    # @order.checkout_date = ""
    @order.order_items.clear
    if @order.save
      flash[:warning] = '請記得重新選擇入住/退房日期，以及修改訂房/服務資料～'
      redirect_to edit_order_path(@order)
    else
      redirect_back fallback_location: order_path(@order)
    end
    # @order.reorder
    # if @order.save
    #   redirect_to weekly_admin_room_calendars_path, notice: "重新下單(#{@order.name})成功"
    # else
    #   redirect_back fallback_location: order_path(@order)
    # end
  end

  def cancel
    @order.cancel
    if @order.save
      redirect_to weekly_admin_room_calendars_path, notice: "訂單(#{@order.name})取消成功"
    else
      redirect_back fallback_location: order_path(@order)
    end

  end

private
  def set_order
    @order = Order.find(params[:id])
    @order.updated_by = current_user.name
  end

  def order_params
    params.require(:order).permit(:checkin_date, :checkout_date, :aasm_state, :source,
      :room_subtotal, :bed_subtotal, :service_subtotal, :total, :downpay, :credit_card,
      :balance, :pay_type, :pay_info, :client_id,
      :name, :sex, :mobile, :country, :id_no, :birthday, :job, :tel, :address, :email, :reminder, :note,
      :adult_subtotal, :kid_subtotal, :baby_subtotal)
  end

  # 回傳「入住日期」至「退房日期」的所有日期
  def get_order_dates
    order_days = []
    if params.has_key?(:checkin_date) && params[:checkin_date].size > 0
      begin_day = Date.parse(params[:checkin_date])
      order_days << begin_day

      if params.has_key?(:checkout_date) && params[:checkout_date].size > 0
        end_day = Date.parse(params[:checkout_date])

        day = begin_day.tomorrow
        until day >= end_day do
          order_days << day
          day = day.tomorrow
        end
      end
    end

    order_days
  end

  def get_room_items(order_days)
    rooms = Room.all

    calendar_items = []
    rooms.each do |room|
      room_days = []
      order_days.each do | day |
        item = CartItem.new
        item.day = day

app/helpers/orders_helper.rb
module OrdersHelper

  def render_order_state(order)
    I18n.t("orders.order_state.#{order.aasm_state}")
  end

end

app/views/orders/_bakform.html.erb
<%= simple_form_for order do |f| %>

  <h4>客戶資料</h4>
  <div class="form-group form-inline">
    <div class="row">
      <div class="col-md-4">
        <%= f.input :client_id, as: :hidden %>
        <%= f.input :aasm_state, as: :hidden, input_html: { value:"order_placed" }%>
        <%= f.input :name, required: true, class: "form-control" %>
        <%= link_to("查詢", search_clients_orders_path, remote: true, class: "btn btn-primary", id: "search_name") %>
      </div>
      <div class="col-md-4"><%= f.input :mobile, required: true, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :sex, collection: [ "男", "女", "第三性"], prompt: "---選擇性別---", class: "form-control" %></div>
    </div>

    <br/>
    <div class="row">
      <div class="col-md-4"><%= f.input :country, priority: [ "台灣" ], collection: [ "台灣", "香港", "日本", "韓國", "大陸"], prompt: "---選擇國家---", class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :id_no, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :email, class: "form-control" %></div>
    </div>

    <br/>
    <div class="row">
      <div class="col-md-4"><%= f.input :job, collection: [ "士", "農", "工", "商", "其他"], prompt: "---選擇職業---", class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :birthday, as: :string, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :tel, class: "form-control" %></div>
    </div>

  </div>

  <hr/><h4>訂單資料</h4>
  <div class="form-group form-inline" >
    訂單日期：<%= Date.today %>
    <div class="row">
      <div class="col-md-4"><%= f.input :checkin_date, as: :string, required: true, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :checkout_date, as: :string, required: true, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :source, collection: [ "電話", "官網", "現場", "Booking.com", "Ctrip"], prompt: "---選擇來源---", class: "form-control" %> </div>

    </div>
  </div>

  <hr/><h4>房型設定</h4>
  <div class="form-group form-inline">
    <div class="row">
      <div class="col-md-4">
        <%= link_to("新增房間", list_rooms_orders_path, remote: true, class: "btn btn-primary", id: "list_rooms") %>
      </div>
      <div class="col-md-4"></div>
      <div class="col-md-4"></div>
    </div>
  </div>

  <h5>房間列表</h5>
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>日期</th>
        <th>房間</th>
        <th>金額</th>
        <th>加床費</th>
        <th>大人</th>
        <th>小孩</th>
        <th>幼兒</th>
      </tr>
    </thead>
    <tbody id="rooms_table"></tbody>
  </table>


  <hr/><h4>房間服務</h4>
  <div class="form-group form-inline">
    <div class="row">
      <div class="col-md-4">
        <%= link_to("新增服務", list_services_orders_path, remote: true, class: "btn btn-primary", id: "list_services") %>
      </div>
      <div class="col-md-4">
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <h5>服務列表</h5>
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>日期</th>
        <th>名稱</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody id="services_table"></tbody>
 </table>


  <hr/><h4>付款資料</h4>
  <div class="form-group form-inline">
    <div class="row">
      <div class="col-md-4"><%= f.input :room_subtotal, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :bed_subtotal, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :service_subtotal, class: "form-control" %></div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-4"><%= f.input :total, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :downpay, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :credit_card, class: "form-control" %></div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-4"><%= f.input :balance, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :pay_type, collection: [ "現金", "信用卡", "其他"], prompt: "---選擇支付方式---", class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :pay_info, class: "form-control" %></div>
    </div>

  </div>

  <hr/><h4>其他資料</h4>
  <div class="form-group form-inline">
    <div class="row">
      <div class="col-md-4"><%= f.input :adult_subtotal, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :kid_subtotal, class: "form-control" %></div>
      <div class="col-md-4"><%= f.input :baby_subtotal, class: "form-control" %></div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-6"><%= f.input :reminder, class: "form-control", input_html: {size:50} %></div>
      <div class="col-md-6"><%= f.input :note, class: "form-control", input_html: {size:50} %></div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-6"><%= f.button :submit, "新增訂單", class: "btn btn-success", :disable_with => "Submiting..." %></div>

    </div>

  </div>

  <hr/><h4>訂房紀錄</h4>
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>訂單入住日</th>
        <th>訂單退房日</th>
        <th>住房日期</th>
        <th>訂單金額</th>
        <th>房號─房型</th>
        <th>提醒(外)</th>
        <th>備註(內)</th>
      </tr>
    </thead>
    <tbody>
      <% if @client.present? && @client.orders.present? %>
        <% @client.orders.each do |order| %>
          <% order.room_items.each do |item| %>
            <tr>
              <td><%= order.checkin_date %></td>
              <td><%= order.checkout_date %></td>
              <td><%= item.day %></td>
              <td><%= order.total %></td>
              <td><%= item.name %></td>
              <td><%= order.client.reminder %></td>
              <td><%= order.client.note %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>

    </tbody>
  </table>

<% end %>

<script type="text/javascript">

  $("#search_name").click(function appendNameParam(){
    var client_name = $("#order_name").val().trim();
    var search_url = "/orders/search_clients";
    if (client_name.length > 0) {
      search_url += "?name="+ client_name;
    }
    $("#search_name").attr("href",search_url);
  });

  $("#list_services").click(function appendParams(){
    var checkin_date = $("#order_checkin_date").val().trim();
    var checkout_date = $("#order_checkout_date").val().trim();
    var list_services_url = "/orders/list_services";
    if (checkin_date.length > 0) {
      list_services_url += "?checkin_date="+ checkin_date + "&checkout_date=" + checkout_date;
      $("#list_services").attr("href",list_services_url);
    } else {

    }
  });

  $("#list_rooms").click(function appendParams(){
    var checkin_date = $("#order_checkin_date").val().trim();
    var checkout_date = $("#order_checkout_date").val().trim();
    var list_rooms_url = "/orders/list_rooms";
    if (checkin_date.length > 0) {
      list_rooms_url += "?checkin_date="+ checkin_date + "&checkout_date=" + checkout_date;
      $("#list_rooms").attr("href",list_rooms_url);
    } else {

    }
  });

  $('#order_checkin_date').datepicker({
    format: "yyyy-mm-dd",
    language: "zh-TW",
    autoclose: true,
    todayHighlight: true,
    toggleActive: true
  });

  $('#order_checkout_date').datepicker({
    format: "yyyy-mm-dd",
    language: "zh-TW",
    autoclose: true,
    todayHighlight: true,
    toggleActive: true
  });

  $('#order_birthday').datepicker({
    format: "yyyy-mm-dd",
    language: "zh-TW",
    autoclose: true,
    todayHighlight: true,
    toggleActive: true
  });

  $("#order_room_subtotal").blur(function (){
    updatePayment();
  });

  $("#order_bed_subtotal").blur(function (){
    updatePayment();
  });

  $("#order_service_subtotal").blur(function (){
    updatePayment();
  });

  $("#order_downpay").blur(function (){
    updatePayment();
  });

  $("#order_credit_card").blur(function (){
    updatePayment();
  });

  <!--計算總額、餘額 -->
  function updatePayment(){
    var roomSubtotal = parseInt($("#order_room_subtotal").val());
    var bedSubtotal = parseInt($("#order_bed_subtotal").val());
    var serviceSubtotal = parseInt($("#order_service_subtotal").val());

    var downpay = parseInt($("#order_downpay").val());
    var creditCard = parseInt($("#order_credit_card").val());

    var total = roomSubtotal + bedSubtotal + serviceSubtotal;
    $("#order_total").val(total);
    var balance = total - downpay - creditCard;
    $("#order_balance").val(balance);
  }

</script>

app/views/orders/_listroomsmodalupdate.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="clientModalLabel">更新房間列表設定</h4>
    </div>
    <div class="modal-body">
      <table class="table table-bordered table-hover">
        <thead>
          <tr class="active">
            <th>項目/日期</th>
            <% @order_days.each do |day| %>
              <th><%= day %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @calendar_items.each do | room_days | %>
              <tr>
                <% index = 0 %>
                <% room_days.each do | item | %>
                  <% if index == 0 %>
                    <td><%= item.name %></td>
                  <% end %>
                  <% index += 1 %>

                  <% if item.price == RoomCalendar::Occupaied_Price %>
                    <td>已訂</td>
                  <% else %>
                    <% td_id = "#{item.day}-#{item.item_id}" %>
                    <td data-id="<%= td_id %>">
                      <div class="form-group add-form">
                        <%= form_with model: item, url: add_order_item_order_path(item.item_id), method: :post do |f| %>
                          <%= f.label :price, "價格:" %>
                          <%= f.text_field :price, size: "5x10"%>
                          <%= f.label :add_bed_no, "床數:" %>
                          <%= f.text_field :add_bed_no, size: "5x10"%>
                          <%= f.label :add_bed_fee, "床費:" %>
                          <%= f.text_field :add_bed_fee, size: "5x10"%>
                          <br/>
                          <%= f.label :adult_no, "大人:" %>
                          <%= f.text_field :adult_no, size: "5x10"%>
                          <%= f.label :kid_no, "小孩:" %>
                          <%= f.text_field :kid_no, size: "5x10"%>
                          <%= f.label :baby_no, "嬰兒:" %>
                          <%= f.text_field :baby_no, size: "5x10"%>

                          <%= f.hidden_field :day %>
                          <%= f.hidden_field :kind %>
                          <%= f.hidden_field :name %>
                          <%= f.hidden_field :item_id %>
                          <input type="hidden" name="order_id" value="<%= order.id %>">
                          <input type="hidden" name="back_path" value="<%= back_path %>" id="back_path">

                          <%= f.submit "新增", class: "btn btn-primary"%>
                        <% end %>
                      </div>

                    </td>

                  <% end %>

                <% end %>
              </tr>
          <% end %>

        </tbody>
      </table>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal" id="close-btn" onclick="redirect_to_update()">完成</button>
    </div>
  </div>
</div>

<script type="text/javascript">
  function redirect_to_update() {
    var back_path = $("#back_path").val().trim();
    window.location.href = back_path;
  };

</script>

app/views/orders/add_order_item.js.erb
<% if @kind == CartItem::Room_Type %>
  var td_selector = "td[data-id=" + "<%= @td_id %>" + "]";
  $(td_selector).css('background-color', 'lightGray');
  var td_input = td_selector + " input";
  $(td_input).prop("disabled", true);
  var td_submit = td_selector + " input[name='commit']";
  $(td_submit).hide('fast');
<% elsif @kind == CartItem::Service_Type %>
  
<% else %>

<% end %>

app/views/orders/add_to_cart.js.erb
<% if @kind == CartItem::Room_Type %>
  <%= render "save" , actionName: 'add_room' %>
<% elsif @kind == CartItem::Service_Type %>
  <%= render "save" , actionName: 'add_service' %>
<% else %>

<% end %>