config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users
    resources :services
    resources :rooms
    resources :room_calendars do
      get  :calendar, on: :collection
      get  :monthly, on: :collection
      get  :weekly, on: :collection
      member do
        post :to_dealday
        post :to_holiday
        post :to_hotday
        post :to_weekday
      end
    end

  end

  resources :dashboard

  resources :clients do
    get :search, on: :collection
  end

  resources :orders do
    get :search_clients, on: :collection
    get :list_services, on: :collection
    get :list_rooms, on: :collection
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member

    get :list_services_update, on: :collection
    get :list_rooms_update, on: :collection
    post :add_order_item, on: :member
    delete :remove_order_item, on: :member

    get :daily, on: :collection
    get :pending, on: :collection
    get :unpaid, on: :collection

    member do
      post :down_pay
      # post :full_pay
      post :check_in
      post :check_out
      post :suspend
      post :reorder
      post :cancel
    end
  end

  resources :statistics do
    get :daily, on: :collection
    get :weekly, on: :collection
    get :monthly, on: :collection
    get :yearly, on: :collection
  end

  resources :print do
    get :orders, on: :collection
    get :abstract, on: :collection
    get :clients, on: :collection
    get :export, on: :collection
  end

  # root 'dashboard#index'
  root 'admin/room_calendars#weekly'
end

app/models/room_calendar.rb
class RoomCalendar < ApplicationRecord
  extend Utility

  ListPrice_Mode = 3
  Holiday_Mode = 2
  Hotday_Mode  = 1
  Weekday_Mode = 0

  Occupaied_Price = -1

  def room_summary(room_no)
    room_hash = get_room_hash(room_no)
    summary = room_hash["summary"].presence
  end

  def get_room_hash(room_no)
    room_hash = {}
    room_json = ""
    case room_no
      when "301"
        room_json = r301
      when "302"
        room_json = r302
      when "303"
        room_json = r303
      when "305"
        room_json = r305
      when "306"
        room_json = r306
      when "101"
        room_json = r101
      when "102"
        room_json = r102
      when "103"
        room_json = r103
      when "105"
        room_json = r105
      when "201"
        room_json = r201
      when "202"
        room_json = r202
      when "203"
        room_json = r203
      when "205"
        room_json = r205
      else
        room_json = ""
    end

    if room_json.present?
      # json to hash
      room_hash = JSON.parse room_json.gsub!('=>', ':')
    end
    room_hash
  end


  def get_price(room_no)
    price = 0
    case day_mode
    when ListPrice_Mode
      price = Room.find_by_no(room_no).list_price
    when Holiday_Mode
      price = Room.find_by_no(room_no).holiday_price
    when Hotday_Mode
      price = Room.find_by_no(room_no).hotday_price
    else
      price = Room.find_by_no(room_no).weekday_price
    end
    price
  end

  def is_occupaied?(room_no)
    is_occupaied = false
    case room_no
    when "301"
      is_occupaied = r301.present?
    when "302"
      is_occupaied = r302.present?
    when "303"
      is_occupaied = r303.present?
    when "305"
      is_occupaied = r305.present?
    when "306"
      is_occupaied = r306.present?
    when "101"
      is_occupaied = r101.present?
    when "102"
      is_occupaied = r102.present?
    when "103"
      is_occupaied = r103.present?
    when "105"
      is_occupaied = r105.present?
    when "201"
      is_occupaied = r201.present?
    when "202"
      is_occupaied = r202.present?
    when "203"
      is_occupaied = r203.present?
    when "205"
      is_occupaied = r205.present?
    else
      is_occupaied = false
    end
    is_occupaied

  end

  def to_dealday
    self.update_columns(day_mode: ListPrice_Mode)
  end

  def to_holiday
    self.update_columns(day_mode: Holiday_Mode)
  end

  def to_hotday
    self.update_columns(day_mode: Hotday_Mode)
  end

  def to_weekday
    self.update_columns(day_mode: Weekday_Mode)
  end

  # 輸出成csv格式 
  def self.to_csv(is_4_db=false, options = {})
    desired_columns = ["day", "day_mode", "day_info"]
    export_columns = ["日期", "日期型態", "備註"]

    to_csv_string(desired_columns, export_columns)
  end

end

app/controllers/admin/room_calendars_controller.rb
class Admin::RoomCalendarsController < ApplicationController
  before_action :authenticate_user!
  # before_action :admin_required

  before_action :set_room_calendar, only: [:to_dealday, :to_holiday, :to_hotday, :to_weekday, :edit]
  before_action :set_search_date, only: [:weekly, :monthly, :index]

  helper_method :get_color

  # 行事曆設定
  def index
    # @room_calendars = RoomCalendar.all.order(:day)
    @room_calendars = RoomCalendar.where("day >= :start_date AND day <= :end_date",
      {start_date: @search_date.beginning_of_year, end_date: @search_date.end_of_year}).order(:day)
  end

  # 依房間查詢(月曆形式)
  def calendar
    @room_no = "r301"
    @room_no = params[:room] if params.has_key?(:room) && params[:room].present?
    @events_url = "/admin/room_calendars/calendar.json?room=#{@room_no}"
    # @room_calendars = RoomCalendar.select("id, day, day_info, #{@room_no} AS title")
    @room_calendars = RoomCalendar.select("id, day, day_info, #{@room_no}, #{@room_no} AS title, #{@room_no} AS color, #{@room_no} AS url")
      .where("day >= :start_date AND day <= :end_date",
      {start_date: Date.current.beginning_of_month, end_date: Date.current.end_of_month}).order(:day)

    @room_calendars.each do |cal|
      room_hash = cal.get_room_hash(@room_no[1,3])
      cal.title = room_hash["summary"]
      order_id = (room_hash["order_id"].present?) ? room_hash["order_id"] : 0

      cal.url = order_path(order_id)
      # cal.url = link_to("", order_path(order_id), remote: true)
      index = (room_hash["order_id"].present?) ? room_hash["order_id"]%10 : 0
      cal.color = get_color(index)
    end

  end

  def get_color(index)
    td_bgcolors = ["lightcyan", "lightblue", "palegreen", "lightyellow", "lightpink", "lavender" ,"lightgray", "lightgreen", "yellow", "lightskyblue"]
    index %= 10
    td_bgcolors[index]
  end

  # 當周訂房狀況
  def weekly
    @room_calendars = RoomCalendar.where("day >= :start_date AND day <= :end_date",
      {start_date: @search_date.beginning_of_week, end_date: @search_date.end_of_week}).order(:day)
  end

  # 當月訂房狀況
  def monthly
    @room_calendars = RoomCalendar.where("day >= :start_date AND day <= :end_date",
      {start_date: @search_date.beginning_of_month, end_date: @search_date.end_of_month}).order(:day)
  end

  def to_dealday
    @room_calendars.to_dealday

    redirect_to calendar_admin_room_calendars_path
  end

  def to_holiday
    @room_calendars.to_holiday

    redirect_to calendar_admin_room_calendars_path
  end

  def to_hotday
    @room_calendars.to_hotday

    redirect_to calendar_admin_room_calendars_path
  end

  def to_weekday
    @room_calendars.to_weekday

    redirect_to calendar_admin_room_calendars_path
  end

  private

  def set_room_calendar
    @room_calendars = RoomCalendar.find(params[:id])
  end

  # def room_calendar_params
  #   params.require(:room_calendar).permit(:day, :day_mode, :day_info)
  # end

end

app/helpers/admin/room_calendars_helper.rb
module Admin::RoomCalendarsHelper

  def render_tr_class(calendar)
    case calendar.day_mode
      when 1
        "success"
      when 2
        "warning"
      when 3
        "danger"
      else
        ""
    end
  end

  def render_summary_td(room_calendar, room_no)
    # td_bgcolors = ["lightcyan", "lightblue", "palegreen", "lightyellow", "lightpink", "lavender" ,"lightgray", "lightgreen", "yellow", "lightskyblue"]
    room_hash = room_calendar.get_room_hash(room_no)
    if room_hash.empty?
      content_tag(:td, "")
    else
      summary = room_hash["summary"].presence
      order_id = (room_hash["order_id"].present?) ? room_hash["order_id"] : 0
      index = (room_hash["order_id"].present?) ? room_hash["order_id"]%10 : 0
      # content_tag(:td, summary, bgcolor: get_color(index))
      # content_tag(:td, link_to(summary, order_path(order_id)), bgcolor: get_color(index))
      content_tag(:td, link_to(summary, order_path(order_id), remote: true), bgcolor: get_color(index))
    end
  end

  def render_day_mode(calendar)
    case calendar.day_mode
      when 1
        "寒暑假旺日"
      when 2
        "週六假日/連假"
      when 3
        "元旦/春節連假"
      else
        "平日"
    end
  end

end

app/views/admin/room_calendars/_room_calendar.html.erb
<tr>
  <td><%= render_day(room_calendar.day) %></td>
  <%= render_summary_td(room_calendar, "301") %>
  <%= render_summary_td(room_calendar, "302") %>
  <%= render_summary_td(room_calendar, "303") %>
  <%= render_summary_td(room_calendar, "305") %>
  <%= render_summary_td(room_calendar, "306") %>
  <%= render_summary_td(room_calendar, "101") %>
  <%= render_summary_td(room_calendar, "102") %>
  <%= render_summary_td(room_calendar, "103") %>
  <%= render_summary_td(room_calendar, "105") %>
  <%= render_summary_td(room_calendar, "201") %>
  <%= render_summary_td(room_calendar, "202") %>
  <%= render_summary_td(room_calendar, "203") %>
  <%= render_summary_td(room_calendar, "205") %>
</tr>

app/views/admin/room_calendars/calendar.html.erb
<div class="col-md-10 col-md-offset-1">
  <h3>依房間查詢 (<%= @room_no.upcase %>)</h3>

  <div id="events_url" data-events_url="<%= @events_url %>" />

  選擇房間：
  <div class="btn-group" role="group" aria-label="...">
    <%= link_to("R301", calendar_admin_room_calendars_path(room: 'r301'), method: :get, class: "btn btn-default")%>
    <%= link_to("R302", calendar_admin_room_calendars_path(room: 'r302'), method: :get, class: "btn btn-default")%>
    <%= link_to("R303", calendar_admin_room_calendars_path(room: 'r303'), method: :get, class: "btn btn-default")%>
    <%= link_to("R305", calendar_admin_room_calendars_path(room: 'r305'), method: :get, class: "btn btn-default")%>
    <%= link_to("R306", calendar_admin_room_calendars_path(room: 'r306'), method: :get, class: "btn btn-default")%>
    <%= link_to("R101", calendar_admin_room_calendars_path(room: 'r101'), method: :get, class: "btn btn-default")%>
    <%= link_to("R102", calendar_admin_room_calendars_path(room: 'r102'), method: :get, class: "btn btn-default")%>
    <%= link_to("R103", calendar_admin_room_calendars_path(room: 'r103'), method: :get, class: "btn btn-default")%>
    <%= link_to("R105", calendar_admin_room_calendars_path(room: 'r105'), method: :get, class: "btn btn-default")%>
    <%= link_to("R201", calendar_admin_room_calendars_path(room: 'r201'), method: :get, class: "btn btn-default")%>
    <%= link_to("R202", calendar_admin_room_calendars_path(room: 'r202'), method: :get, class: "btn btn-default")%>
    <%= link_to("R203", calendar_admin_room_calendars_path(room: 'r203'), method: :get, class: "btn btn-default")%>
    <%= link_to("R205", calendar_admin_room_calendars_path(room: 'r205'), method: :get, class: "btn btn-default")%>

  </div>
  <br/>


  <br/><div id="calendar"></div><br/>

</div>

<script type="text/javascript">
  events_url = $("#events_url").data("events_url");

  $('#calendar').fullCalendar({
    locale: 'zh-TW',
    height: 500,

    header: {
      left: '',
      center: 'title',
      right: ''
    },

    events: events_url
  });

</script>

app/views/admin/room_calendars/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <h2>行事曆設定</h2>

  <table class="table" >
    <thead>
      <tr>
        <td class="text-left"><%= link_to("上一年", admin_room_calendars_path(search_date: @search_date.prev_year), method: :get, class: "btn btn-primary")%></td>
        <td class="text-right"><%= link_to("下一年", admin_room_calendars_path(search_date: @search_date.next_year), method: :get, class: "btn btn-primary")%></td>
      </tr>
    </thead>
  </table>


  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>日期</th>
        <th>型態</th>
        <th>備註</th>
        <th>設定</th>
      </tr>
    </thead>
    <tbody>
      <% @room_calendars.each do |room_calendar| %>
        <tr class="<%= render_tr_class(room_calendar) %>" >
          <td><%= render_fullday(room_calendar.day) %></td>
          <td><%= render_day_mode(room_calendar) %></td>
          <td><%= room_calendar.day_info %></td>
          <td>
            <%= link_to("轉平日", to_weekday_admin_room_calendar_path(room_calendar), method: :post, class: "btn btn-default")%>
            <%= link_to("轉旺日", to_hotday_admin_room_calendar_path(room_calendar), method: :post, class: "btn btn-default btn-success")%>
            <%= link_to("轉假日", to_holiday_admin_room_calendar_path(room_calendar), method: :post, class: "btn btn-default btn-warning")%>
            <%= link_to("轉定價", to_dealday_admin_room_calendar_path(room_calendar), method: :post, class: "btn btn-default btn-danger")%>

          </td>
        </tr>

      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/room_calendars/monthly.html.erb
<div class="col-md-12 col-md-offset-0">
  <h4>當月訂房狀況</h4>
  <div class="row">
    <div class="col-md-3">
      <!--日期搜尋功能(含顯示月曆功能)-->
      <%= render partial: "common/searchday", locals:{search_path: monthly_admin_room_calendars_path, search_date: @search_date} %>
    </div>

    <div class="col-md-1"><%= link_to("上一月", monthly_admin_room_calendars_path(search_date: @search_date.prev_month), method: :get, class: "btn btn-primary")%></div>
    <div class="col-md-1"><%= link_to("下一月", monthly_admin_room_calendars_path(search_date: @search_date.next_month), method: :get, class: "btn btn-primary")%></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-2">今天日期：<%= Date.today %></div>    <div class="col-md-1"></div>

  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th>日期</th>
        <th>301<br/>雅緻二人房</th>
        <th>302<br/>經典二人房</th>
        <th>303<br/>經典二人房</th>
        <th>305<br/>浪漫情人房</th>
        <th>306<br/>溫馨二人房</th>
        <th>101<br/>迎曦四人房</th>
        <th>102<br/>迎曦二人房</th>
        <th>103<br/>迎曦四人房</th>
        <th>105<br/>豪華四人房</th>
        <th>201<br/>迎曦六人房</th>
        <th>202<br/>迎曦六人房</th>
        <th>203<br/>迎曦六人房</th>
        <th>205<br/>豪華八人房</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "room_calendar", collection: @room_calendars %>
    </tbody>
  </table>
</div>

<!--bootstrap modal放的地方，初始值沒有任何東西-->
<div id="showOrderModal" class="modal fade" role="dialog"></div>

app/views/admin/room_calendars/weekly.html.erb
<div class="col-md-12 col-md-offset-0">
  <h3>當週訂房狀況</h3>
  <div class="row">
    <div class="col-md-3">
      <!--日期搜尋功能(含顯示月曆功能)-->
      <%= render partial: "common/searchday", locals:{search_path: weekly_admin_room_calendars_path, search_date: @search_date} %>
    </div>

    <div class="col-md-1"><%= link_to("上一週", weekly_admin_room_calendars_path(search_date: @search_date.prev_week), method: :get, class: "btn btn-primary")%></div>
    <div class="col-md-1"><%= link_to("下一週", weekly_admin_room_calendars_path(search_date: @search_date.next_week), method: :get, class: "btn btn-primary")%></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-1"></div>
    <div class="col-md-2">今天日期：<%= Date.today %></div>    <div class="col-md-1"></div>

  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr class="active">
        <th width="7%">日期</th>
        <th width="7%">301<br/>雅緻二人房</th>
        <th width="7%">302<br/>經典二人房</th>
        <th width="7%">303<br/>經典二人房</th>
        <th width="7%">305<br/>浪漫情人房</th>
        <th width="7%">306<br/>溫馨二人房</th>
        <th width="7%">101<br/>迎曦四人房</th>
        <th width="7%">102<br/>迎曦二人房</th>
        <th width="7%">103<br/>迎曦四人房</th>
        <th width="7%">105<br/>豪華四人房</th>
        <th width="7%">201<br/>迎曦六人房</th>
        <th width="7%">202<br/>迎曦六人房</th>
        <th width="7%">203<br/>迎曦六人房</th>
        <th width="7%">205<br/>豪華八人房</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "room_calendar", collection: @room_calendars %>
    </tbody>
  </table>
</div>

<!--bootstrap modal放的地方，初始值沒有任何東西-->
<div id="showOrderModal" class="modal fade" role="dialog"></div>