config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users
    resources :services
    resources :rooms
    resources :room_calendars do
      get  :calendar, on: :collection
      get  :monthly, on: :collection
      get  :weekly, on: :collection
      member do
        post :to_dealday
        post :to_holiday
        post :to_hotday
        post :to_weekday
      end
    end

  end

  resources :dashboard

  resources :clients do
    get :search, on: :collection
  end

  resources :orders do
    get :search_clients, on: :collection
    get :list_services, on: :collection
    get :list_rooms, on: :collection
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member

    get :list_services_update, on: :collection
    get :list_rooms_update, on: :collection
    post :add_order_item, on: :member
    delete :remove_order_item, on: :member

    get :daily, on: :collection
    get :pending, on: :collection
    get :unpaid, on: :collection

    member do
      post :down_pay
      # post :full_pay
      post :check_in
      post :check_out
      post :suspend
      post :reorder
      post :cancel
    end
  end

  resources :statistics do
    get :daily, on: :collection
    get :weekly, on: :collection
    get :monthly, on: :collection
    get :yearly, on: :collection
  end

  resources :print do
    get :orders, on: :collection
    get :abstract, on: :collection
    get :clients, on: :collection
    get :export, on: :collection
  end

  # root 'dashboard#index'
  root 'admin/room_calendars#weekly'
end

app/views/common/_clienttable.html.erb
<table class="table table-bordered">
  <thead>
  </thead>
  <tbody>
    <tr class="active"><td class="text-center" colspan="6">客戶資料</td></tr>
    <tr>
      <td width="10%" class="active">姓名</td><td width="23%" ><%= client.name %></td>
      <td width="10%" class="active">手機</td><td width="23%" ><%= client.mobile %></td>
      <td width="10%" class="active">性別</td><td width="23%" ><%= client.sex %></td>
    </tr>
    <tr>
      <td width="10%" class="active">國籍</td><td width="23%" ><%= client.country %></td>
      <td width="10%" class="active">身分證/護照</td><td width="23%" ><%= client.id_no %></td>
      <td width="10%" class="active">生日</td><td width="23%" ><%= client.birthday %></td>
    </tr>
    <tr>
      <td width="10%" class="active">地址</td><td width="23%" colspan="3" ><%= client.address %></td>
      <td width="10%" class="active">E-mail</td><td width="23%" ><%= client.tel %></td>
    </tr>
    <tr>
      <td width="10%" class="active">提醒</td><td width="23%" colspan="3" ><%= client.reminder %></td>
      <td width="10%" class="active"></td><td width="23%" ></td>
    </tr>
    <% if show_note %>
      <tr>
        <td width="10%" class="active">備註</td><td width="23%" colspan="3" ><%= client.note %></td>
        <td width="10%" class="active">電話</td><td width="23%" ><%= client.tel %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2018 SHC
    <br>Design by <a href="">chen4hao</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= render_system_name %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">訂房/訂單管理
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("訂單登入", new_order_path )%></li>
            <li class="divider"> </li>
            <li> <%= link_to("當月訂房狀況", monthly_admin_room_calendars_path )%></li>
            <li> <%= link_to("依房間查詢", calendar_admin_room_calendars_path ) %></li>
            <li> <%= link_to("未付訂清單", unpaid_orders_path ) %></li>
            <li> <%= link_to("待處理訂單", pending_orders_path ) %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">接待/客戶管理
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("Check-in(當日入住名單)", daily_orders_path )%></li>
            <li class="divider"> </li>
            <li> <%= link_to("依日期查詢", orders_path )%></li>
            <li> <%= link_to("依客戶查詢", search_clients_path ) %></li>
            <li> <%= link_to("列出所有客戶", clients_path ) %></li>
          </ul>
        </li>
      </ul>

      <% if current_user && current_user.admin? %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">統計報表
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("日報", daily_statistics_path )%></li>
            <li> <%= link_to("週報", weekly_statistics_path )%></li>
            <li> <%= link_to("月報", monthly_statistics_path ) %></li>
            <li> <%= link_to("年報", yearly_statistics_path ) %></li>
          </ul>
        </li>
      </ul>
      <% end %>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">表單列印
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("當日房客資料表", clients_print_index_path )%></li>
            <li> <%= link_to("當日住宿簡表", abstract_print_index_path )%></li>
            <li> <%= link_to("當日房客住宿明細", orders_print_index_path ) %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">相關連結
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "世界時間", "https://tw.piliapp.com/time-now/", target: "_blank" %></li>
            <li><%= link_to "中央氣象局", "https://www.cwb.gov.tw/V7/forecast/", target: "_blank" %></li>
            <li><%= link_to "一週天氣預報", "https://www.cwb.gov.tw/V7/forecast/week/week.htm#area2", target: "_blank" %></li>
            <li><%= link_to "颱風警報", "https://www.cwb.gov.tw/V7/prevent/typhoon/ty.htm", target: "_blank" %></li>
            <li class="divider"> </li>

            <li><%= link_to "觀星天相圖", "", target: "_blank" %></li>
            <li><%= link_to "Windty", "https://www.windy.com/?23.975,120.941,5", target: "_blank" %></li>
            <li class="divider"> </li>

            <li><%= link_to "英漢字典", "https://tw.voicetube.com/definition/", target: "_blank" %></li>
            <li><%= link_to "高速公路路況", "https://1968.freeway.gov.tw/traffic/index/fid/10010", target: "_blank" %></li>
            <li><%= link_to "Google map", "https://www.google.com.tw/maps/@24.0456979,121.1562197,17z?hl=zh-TW", target: "_blank" %></li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">系統管理
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("房價管理", admin_rooms_path )%></li>
            <li> <%= link_to("服務管理", admin_services_path )%></li>
            <li class="divider"> </li>
            <li> <%= link_to("行事曆管理", admin_room_calendars_path )%></li>
            <li class="divider"> </li>
            <li> <%= link_to("資料備份", export_print_index_path )%></li>
            <li class="divider"> </li>
            <li> <%= link_to("系統更新列表", dashboard_index_path ) %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
              <% if !current_user.title.blank? %>
                (<%= current_user.title %>)
              <% end %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li> <%= link_to("帳號管理", admin_users_path )%></li>
                <li class="divider"> </li>
              <% end %>
              <li> <%= link_to("帳號設定", edit_user_registration_path )%></li>
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete ) %></li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_ordertable.html.erb
<table class="table table-bordered">
  <thead></thead>
  <tbody>
    <tr class="active"><td class="text-center" colspan="8">功能維護</td></tr>
    <tr>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_placed" || order.aasm_state == "down_paid" ||
               order.aasm_state == "full_paid"    || order.aasm_state == "order_pending" ||
               order.aasm_state == "checked_in" )%>
          <%= link_to("訂單修改", edit_order_path(order), class: "btn btn-primary") %>
        <% else %>
          <%= link_to("訂單修改", edit_order_path(order), class: "btn btn-primary disabled" ) %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_placed") %>
          <%= link_to("付訂", down_pay_order_path(order), method: :post, class: "btn btn-success") %>
        <% else %>
          <%= link_to("付訂", down_pay_order_path(order), method: :post, class: "btn btn-success disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_placed" || order.aasm_state == "down_paid" ||
               order.aasm_state == "full_paid" )%>
          <%= link_to("入住", check_in_order_path(order), method: :post, class: "btn btn-success") %>
        <% else %>
          <%= link_to("入住", check_in_order_path(order), method: :post, class: "btn btn-success disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "checked_in")%>
          <%= link_to("退房", check_out_order_path(order), method: :post, class: "btn btn-success") %>
        <% else %>
          <%= link_to("退房", check_out_order_path(order), method: :post, class: "btn btn-success disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_placed" || order.aasm_state == "down_paid" ||
               order.aasm_state == "full_paid" )%>
          <%= link_to("訂單保留", suspend_order_path(order), method: :post, class: "btn btn-warning") %>
        <% else %>
          <%= link_to("訂單保留", suspend_order_path(order), method: :post, class: "btn btn-warning disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_pending" )%>
          <%= link_to("重新下單", reorder_order_path(order), method: :post, class: "btn btn-primary") %>
        <% else %>
          <%= link_to("重新下單", reorder_order_path(order), method: :post, class: "btn btn-primary disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <% if (order.aasm_state == "order_pending")%>
          <%= link_to("訂單取消", cancel_order_path(order), method: :post, class: "btn btn-warning") %>
        <% else %>
          <%= link_to("訂單取消", cancel_order_path(order), method: :post, class: "btn btn-warning disabled") %>
        <% end %>
      </td>
      <td width="12%" class="text-center" >
        <%= link_to("訂單刪除", order_path(order), class: "btn btn-danger",
                  method: :delete, data: { confirm: "你確定要刪除嗎?" } )%></td>
    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <thead></thead>
  <tbody>
    <tr class="active"><td class="text-center" colspan="6">訂單資料</td></tr>
    <tr>
      <td width="10%" class="active">姓名</td><td width="23%" ><%= order.name %></td>
      <td width="10%" class="active">狀態</td><td width="23%" ><%= render_order_state(order) %></td>
      <td width="10%" class="active">國別</td><td width="23%" ><%= order.country %></td>
    </tr>
    <tr>
      <td width="10%" class="active">日期</td><td width="23%" ><%= order.checkin_date %></td>
      <td width="10%" class="active">手機</td><td width="23%" ><%= order.mobile %></td>
      <td width="10%" class="active">房價</td><td width="23%" ><%= order.room_subtotal%></td>
    </tr>
    <tr>
      <td width="10%" class="active">加床</td><td width="23%" ><%= order.bed_subtotal%>
      <td width="10%" class="active">服務</td><td width="23%" ><%= order.service_subtotal %></td>
      <td width="10%" class="active">總額</td><td width="23%" ><%= order.total %></td>
    </tr>
    <tr>
      <td width="10%" class="active">訂金</td><td width="23%" ><%= order.downpay %></td>
      <td width="10%" class="active">信用卡</td><td width="23%" ><%= order.credit_card %></td>
      <td width="10%" class="active">餘額</td><td width="23%" ><%= order.balance %></td>
    </tr>
    <tr>
      <td width="10%" class="active">備註</td><td width="23%" colspan="3" ><%= order.note %></td>
      <td width="10%" class="active">末5碼</td><td width="23%" ><%= order.pay_info %></td>
    </tr>

  </tbody>
</table>

<table class="table table-bordered table-condensed" id="order_items_table">
  <thead></thead>
  <tbody>
    <tr class="active"><td class="text-center" colspan="7">訂單明細─房間列表</td></tr>
    <tr class="active">
      <th width="20%">日期</th>
      <th width="30%">房間</th>
      <th width="10%">金額</th>
      <th width="10%">加床費</th>
      <th width="10%">大人</th>
      <th width="10%">小孩</th>
      <th width="10%">幼兒</th>
    </tr>
    <%= render partial: "orderitem", collection: order.room_items, as: :item, locals:{ kind: 'Room', deletable: false}  %>

    <tr class="active"><td class="text-center" colspan="7">訂單明細─服務列表</td></tr>
    <%= render partial: "orderitem", collection: order.service_items, as: :item, locals:{ kind: 'Service', deletable: false}  %>

  </tbody>
</table>

app/views/common/_searchday.html.erb
  <div class="form-group search-form">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.label :date_label, "日期:" %>
      <%= f.text_field :search_date, id: "search_date", value: search_date  %>
      <%= f.submit "查詢", class: "btn btn-primary" %>
    <% end %>
  </div>


<script type="text/javascript">
$(document).ready(function(){

  <!-- 點選訂房開始日期跳出小月曆 -->
  $('#search_date').datepicker({
    format: "yyyy-mm-dd",
    language: "zh-TW",
    autoclose: true,
    todayHighlight: true,
    toggleActive: true
  });

});

</script>